#!/bin/sh -e

THIS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
TEST_DIR=$(dirname $THIS_DIR)/tests

export PREFIX=""
if [ -d 'venv' ] ; then
    export PREFIX="venv/bin/"
fi
if [ -d '.venv' ] ; then
    export PREFIX=".venv/bin/"
fi

set -x

PYTHONPATH=$TEST_DIR ${PREFIX}pytest --ignore venv --ignore .venv \
    --cov=apistar_autoapp \
    --cov-report xml:test-results/coverage/coverage.xml \
    --cov-report html:test-results/coverage \
    --cov-report=term-missing \
    --junit-xml=test-results/results.xml ${@}
