#!/bin/sh -e

export PREFIX=""
if [ -d 'venv' ] ; then
    export PREFIX="venv/bin/"
fi
if [ -d '.venv' ] ; then
    export PREFIX=".venv/bin/"
fi

set -x

PYTHONPATH=. ${PREFIX}pytest --ignore venv --ignore .venv --cov=apistar-autoapp --cov=tests --cov-report=term-missing ${@}
