#!/bin/sh -e

export PREFIX=""
if [ -d 'venv' ] ; then
    export PREFIX="venv/bin/"
fi
if [ -d '.venv' ] ; then
    export PREFIX=".venv/bin/"
fi

set -x

PYTHONPATH=. ${PREFIX}pytest --ignore venv --ignore .venv --cov=apistar-autoapp --cov=tests \
    --cov-report xml:test-results/coverage/coverage.xml --cov-report html:test-results/coverage --cov-report=term-missing --junit-xml=test-results/results.xml ${@}
